### ISSUE TITLE
Support double page divs?

### ISSUE THREAD

**Issue by jimmykhlam** [blasten/turn.js#1]
I have a bunch of divs that are currently more like “slides”. That is, each div is a full double page width instead of a single page width. Is there a way to configure the plugin so that it will work with divs that are meant to represent the double page?

```
<div id='magazine'>
    <div> Page 1 and 2 </div>
    <div> Page 3 and 4 </div>
    <div> Page 5 and 6 </div>
</div>
```

This is a great plugin thanks for releasing it!

**Comment by blasten** [comment]
Are the pages images? 
It is possible in both cases.

1) If you are using images:

It would be the same application used for CSS sprites.

Use CSS:

Left page:
background-image:url(double-page.jpg);
background-position:0% 0%;

Right page:
background-image:url(double-page.jpg);
background-position:-50% 0%;

2) Using only HTML:
It is even more easy.
Just separate your HTML in two parts.

Limitation: the first page should be single page, otherwise just turn to page 2.

Let me know, if it's a good solution or not.

Cheers.

**Comment by georgeorgeorge** [comment]
Love the plugin by the way. It's the main reason why I finally joined GitHub!

I was also wondering whether it was possible to have a spread option in this plugin. I have been Ajaxing Adobe Edge animations into the books pages, which the plugin handles brilliantly by the way, but it would be amazing if it could support some sort of spread overlay system where you could have an animation or something that requires 2 pages take over the whole spread.

If it had this feature I would have no qualms over donating time or resources to the project.

I'd love to know your thoughts on this. Keep up the awesome work!

George
