### ISSUE TITLE
Google Chrome 19.0.1084.52

### ISSUE THREAD

**Issue by adastreamer** [blasten/turn.js#101]
https://docs.google.com/document/pub?id=1LpsPYsKHCy6C4GnKKyKkB4GROgnH9amYZmgCSQd2Cpc

**Comment by blasten** [comment]
@adastreamer I reported that bug to the Chromium team, for some reasons they decided to not fix it on the current version (19.0.x), but it's almost fixed in canary 21.0.1140.0.   To solve the problem you have to set acceleration:false in the options.  I wonder why you are seeing that if the hardware acceleration is disabled for Chrome 19. 

You can see more details here: http://code.google.com/p/chromium/issues/detail?id=128488

Would you mind if you type `navigator.userAgent`in the console of developer tools and send me the output?

**Comment by adastreamer** [comment]
I've changed "acceleration" option to "false" and It works fine. Thank you.
