### ISSUE TITLE
Teasing Corner

### ISSUE THREAD

**Issue by sthurer** [blasten/turn.js#108]
Is there anyway to make the corner tease a little bit so that users know to turn it?

**Comment by sthurer** [comment]
I saw the answer for this under closed issues.

**Comment by blasten** [comment]
Great!

**Comment by sthurer** [comment]
Unfortunately it didn't work. I was using 'peel' but I didn't see any
effect.

**Comment by blasten** [comment]
It's only in the 4th release.

**Comment by sthurer** [comment]
I'm pretty sure I'm using the fourth release.

**Comment by blasten** [comment]
@sthurer  how are you using peel?

**Comment by blasten** [comment]
Here is `peel`: www.turnjs.com/samples/magazine

**Comment by emangarcia** [comment]
I am also having a problem implementing the peel effect. Firebug gives me this error: <code>uncaught exception: TurnJsError: peel is an invalid value</code>.

**Comment by sthurer** [comment]
I'm not the greatest javascripter...so I was assuming it was just me.
I had the demo you posted last night working on my local machine, but
as soon as I made any changes (like changing display:spread to
display:single) it stopped working.

**Comment by blasten** [comment]
@emang77  The syntax is `$('selector').turn('peel', 'corner');` so that you should replace corner with **br, bl, tr or tl.**

If you are in the first page and double page, you should only use  **br** or **tr**  
Example : `$('selector').turn('peel', 'br');` 

The documentation has everything you need to make it work, I'm working on the HTML documentation.

**Comment by emangarcia** [comment]
Is there a new version of the fourth release that supports the <code>peel</code> function?

**Comment by blasten** [comment]
@emang77  Yes, it includes the `peel` function.
