### ISSUE TITLE
Having Issues with Peel

### ISSUE THREAD

**Issue by Annodyne** [blasten/turn.js#111]
I'm currently on version 4 and when I call my peel:

$('.ibrochure').turn('peel', 'tr');

No action occurs and no errors are reported.  I've tried several different corner types.  I'm using the 'double' view.  Might that have anything to do with it?

Edit: I'm also making use of absolutely/relatively positioned content in order to achieve some animations.  It's killed the backgrounds on the page turns.  You can see the peel when you mouseover but it's a transparent gradient.  I guess that's the sacrifice.

**Comment by blasten** [comment]
It was reported an issue when the value of the option `page` was different to 1. is it your case?    The background problem seems to be more a CSS problem. People who had a similar problem was because one of these: In turn.js 4 the `.turn-page` was changed to just `.page`. Also, you shouldn't use the subclass `.page-wrapper` because it isn't used in a folded page. So that all you CSS rules wouldn't take place.    The last update of turn.js was two days ago, and it's coming a new one today, are you using 4.05?

**Comment by Annodyne** [comment]
I tried setting the page option to 1, but that didn't seem to help.

The background css problems were definitely of my own design thanks to the absolute positioning, but I've been playing with the page backgrounds all morning and have come to a good resolution among different browsers using alpha colors.

I will keep an eye out for the new version.  I've been referencing the link in my receipt email for updates.  Is that the best way to access the paid updates?

As always, many thanks!

**Comment by blasten** [comment]
I think you might be using an old update, because the peeling method was added later.  Please, send me an email blasten@gmail.com.

**Comment by tuffd** [comment]
Hello,

Can i also send an email, because i have the same trouble ?

Thanks !

**Comment by blasten** [comment]
@tuffd Of course.

**Comment by blasten** [comment]
This issues was solved on turn.js 4.0.6

**Comment by ballaneypranav** [comment]
I'm using 4.1 but it doesn't work.. I want to disable the peel thing..
Code:

$('#flipbook').turn({
    width:720, 
    height:525,
});

$('#flipbook').turn('peel', false);
