### ISSUE TITLE
corner is set to 'bl' or 'br' in start event even when the turning was not started from a corner.

### ISSUE THREAD

**Issue by jedahan** [blasten/turn.js#113]
If you do `$('#flipbook').turn('next')` or `$('#flipbook').turn('previous')` the start event has corner set to bl or br. This messes with ev.preventDefault() in start, which I want to disable corner-hints.

**Comment by jedahan** [comment]
I would fork and submit a pull request with a fix, but turnjs v4 is closed development, even for those that have a license. That's pretty annoying. Why not have a private repository for v4 and add contributors as they buy a license key?

**Comment by blasten** [comment]
@jedahan  is it v3 or v4?

**Comment by jedahan** [comment]
v4

**Comment by blasten** [comment]
Ah I see, yes it's same behavior of v3. It's because when using `next` or `previous` it's using the same corners to go backward or forward in the flipbook.

I'm working on this new docs, http://turnjs.com/wiki/Event:_turning. You can see the event sequence, I want to explain what was my approach, but since I believe in options, I can consider to make that part optional for developers. Something like an option:  `turningCorners:"bl,br"`

**Comment by jedahan** [comment]
yeah being able to have `activeCorners:""` would be helpful. The page turning events should still have `corner:null` when `next` or `previous` is called if they were not called from a corner.

**Comment by blasten** [comment]
Here's the option: http://turnjs.com/docs/Option:_turnCorners

**Comment by jedahan** [comment]
There is no way to set those options to the empty string?

**Comment by blasten** [comment]
@jedahan yes it should always return null when triggering `start` if it isn't from a mouse action.

**Comment by blasten** [comment]
The corner argument of the start event now returns null when using the methods next, previous and page. turn.js 4.0.7

**Comment by jedahan** [comment]
thanks so much!
