### ISSUE TITLE
Zoom still not working in IE8

### ISSUE THREAD

**Issue by zoee** [blasten/turn.js#125]
Hi, you closed my last issue but it wasn't resolved.

I can't get the Zoom to work in IE 8 on the version I have installed at http://www.lincolnshireshowground.co.uk/booklet/  I used the magazine code included in the zip.

Your websites says you support IE8... is there a way to fix this issue?

Thanks :)

**Comment by blasten** [comment]
@zoee I tested it in IE8, http://cl.ly/image/2l1S0P2m3V0N  I didn't  note any issue but could you please describe what issue you get?  Also, it seems like some resources aren't available, for example: 
1. http://www.lincolnshireshowground.co.uk/pages/2.jpg
2. http://www.lincolnshireshowground.co.uk/pages/3.jpg

Another problem, the large images are too heavy, you might need to reduce the DPI (resolution) and/or change the format. Since they are basically vectors, you could use PNG 8, which is optimal for this type of PDF pages.

**Comment by blasten** [comment]
@zoee have you solved the problem?

**Comment by zoee** [comment]
Yes! Downloading the new version solved the IE issue and making the pictures smaller solved the image loading issue!

Thanks :)

**Comment by blasten** [comment]
@zoee Fantastic!
