### ISSUE TITLE
Blurry page when corner peels and 1 pixel vertical center flickering

### ISSUE THREAD

**Issue by jimmykhlam** [blasten/turn.js#157]
When I mouseover a corner to activate the page peeling, that side of the page becomes a little blurry. This is particularly an issue when there is text on that page, which becomes hard to read. 

Also, that blur often comes together with a 1 pixel flicker vertically along the center as the page blurs. 

Please check it out. Thanks!

**Comment by blasten** [comment]
@jimmykhlam This is a common question and I would like to make a final post.

These are unfortunately issues that are far from my hands and optimizations that can be made at this point.

Here there are some issues I have reported to the Chromium team, the people who make Chrome.

1) Pixel problem. The bug is confirmed but it was labeled as untriaged.
1. http://code.google.com/p/chromium/issues/detail?id=129245
2. http://code.google.com/p/chromium/issues/detail?id=140721
3. http://jsfiddle.net/blasten/BDVyu/ 

2) Pages getting blurry.

The page gets blurry because it's the way that most browser vendors figured out to make animations run faster **for now**. In other words to have a more fluent and continuous animation. Turn.js uses CSS3 transformations to make the div elements look like a page. Typically when a css property of position is updated (including transformation) that comes with updating the position of every element of inside (at least from the user point of view). Behind the scenes, what it might be going on is just repainting these inner elements. This fact has a high cost in terms of processing resources, since it might require to make several computations per element. A way that most browsers figured out to run animations a lot faster was to instead of updating and repainting every single element, to make a snapshot (treat the element as a texture instead of vector) so that the repaint can be perform in only one texture.

In some cases like in the Firefox implementation, the snapshot disappears (no blurry) when there isn't more CSS3 transformations to update.  So what we have is not an uniform implementation across the browser platform. Nothing new, but here's what we now:
1. Safari
   Works nice either using hardware acceleration or not.  There isn't neither blurry pages nor pixel jumping vertically.
2. Chrome.
   Animations get blurry only when using the hardware acceleration mode. {acceleration: true} in turn.js
   If you disable the hardware acceleration mode and your content is regular HTML instead of images, then you will have 1 pixel flicker vertically.
3. Firefox
   Using or not using hardware acceleration wouldn't prevent blurry pages.
4. IE 
   No tested yet.

**Comment by jimmykhlam** [comment]
Thanks, appreciate the insight and your support.

**Comment by nicopowa** [comment]
hi ! sorry i'm a bit late :)
this blurry effect still happens in latest versions of Firefox when the page transform begins,
i found a simple fix, it might affect page flip performance, but resolved the problem.

```
// go away firefox css transform blur
if(navigator.userAgent.toLowerCase().indexOf("firefox") != -1) {
    $("#flipbook").css({"filter": "blur(0)", "-webkit-filter": "blur(0)"});
}
```

this css transform bug also moved the page by 1px in some cases,
my problem came from setting the book width at 100% while the parent had an odd width value or the width or height of the book being a float number.
simple fix again :

```
var myDynamicBookWidthValue = parseInt(viewport or parent pixel width);
if(myDynamicBookWidthValue % 2 == 1) myDynamicBookWidthValue--; // no odd width
$("#flipbook").css({width: myDynamicBookWidthValue});
```
