### ISSUE TITLE
text leaking through peeling corner

### ISSUE THREAD

**Issue by Pushplaybang** [blasten/turn.js#166]
Just bought turn.js 4 and using a slightly adjusted version of the magazine example you've included.  Responsiveness is working, and I'm starting to layout pages using actual content instead of just images, and it seems  - when resized down - that the content overflows from the next page, so as the corner peels back there is a large triangle of text below the magazine, I've tried inspecting it in chrome to see if its a css issue and not having much joy.

Any help would be greatly appreciated.

**Comment by blasten** [comment]
I see, you could add an `overflow:hidden` to every page, but that wouldn't solve the problem of having more content that cannot be shown on the actual screen size. There's a plan of developing a tool that will trim the text, so that the extra text can be added to the next pages and so on.

**Comment by Pushplaybang** [comment]
yeah that would  awesome, but after playing with it, I let go of my hopes of containing complex layouts and making them scalable, I need to have live content outside the mag anyway which I'll be switching to for lower level devices like  entry level feature phones etc so its totally cool.

**Comment by RichSharpe** [comment]
"I see, you could add an overflow:hidden to every page, but that wouldn't solve the problem of having more content that cannot be shown on the actual screen size. There's a plan of developing a tool that will trim the text, so that the extra text can be added to the next pages and so on."

Is this now in existence? I have a scenario where I am rendering pages from a external content management system so I do not know how much text etc will be loaded. This would be cool to effectively 'flow' the text/images onto subsequent pages.

**Comment by blasten** [comment]
@RichSharpe I'm really excited about a build-in feature that allows fluid content. It started with the idea of building a Polyfill for CSS3 Regions, and the result was a HTML splitter that runs really fast. It's called the fragment API is part of turn.js 5th release. Coming soon Guys!!!
