### ISSUE TITLE
Does not work with transform:scale(x)

### ISSUE THREAD

**Issue by lawrenceshen** [blasten/turn.js#32]
Hi, turn.js is very impressive! I would love to having it working on my magazine page.
My magazine page uses CSS transform:scale(x) property in order to scale up/down all background images/text, yet maintaining relative positions.  However, this does not seem to work well with turn.js

If i scale up/down the entire container, the 'turn corners' of the pages will be off position.

Would you kindly advise would I should do?  Thanks!

**Comment by blasten** [comment]
I've thought about the best way to provide a functionality for zooming. I hope to provide a feature for that in next versions. It's not an easy issue, I don't really like the idea of using so many transformations over different parts of the magazine. The idea I have is to create a zoom method that will require to disable the flipping effect, because of performance.  Do you think it would work for you?  Something like this:

$('#id').turn('zoom',5);   it will apply scale(5)

**Comment by lawrenceshen** [comment]
Hey Blasten, thanks for replying.
To be honest, the flipping effect is the most impressing effect and I would love to use it even at the cost of performance.  Perhaps there could be a toggle-able mode?
i.e 
var $flipEffectOn = true;
$('#id').turn('zoom',5, $flipEffectOn); will apply scale(5) with flip effect enabled.

**Comment by blasten** [comment]
Ok, I have to think about that!

**Comment by zertol** [comment]
Hello, I'm facing the same issue. Did you ever figure out a way to solve it?
Thank you!
