### ISSUE TITLE
"Cover" Pages Not Remaining Fixed

### ISSUE THREAD

**Issue by wingmanjp** [blasten/turn.js#340]
Hello.

I am using version 4.  I am attempting to keep the outside cover pages (which are larger than the inside pages, visible once the book is open.  I am using Wordpress and have it working, but the covers disappear.

I tried to use the code you offered in issue #147 to dynamically apply the .fixed class with no luck.  I'm no javascript ninja, so it's possible I'm missing something simple.

The site is here: http://bondinchair.com if you want to take a look.

Thanks!

**Comment by blasten** [comment]
The only way is to use the fixed class because turn.js uses a dynamic approach that will remove all the pages from the DOM tree as the user turns the pages. This is done to release memory resources and overall have a more stable navigation.  However, `.fixed` is the way to tell turn.js: " I don't care"
