### ISSUE TITLE
Pages with class="fixed" flashing during animation in Internet Explorer

### ISSUE THREAD

**Issue by richardwestenra** [blasten/turn.js#375]
I'm using the fixed class to keep inner cover pages visible when the book is open. However they briefly disappear during any page turn animation or corner curl. It happens only in internet explorer (any version - I've tested IE7,8,9,10). I'm stumped as to why. Any help would be massively appreciated. Thanks!

Code gist demo: http://bl.ocks.org/richardwestenra/6041734
Working example: http://test.distilled.net/staples/smells/

**Comment by davbaron** [comment]
Hi Richard,

I too found that the 'fixed' class did not really 'work' as expected.  In my own case, my 'books' are never 'closed', i.e., the user never sees the front or back 'covers' of the book.  So, to avoid the stuff you're seeing, I used the following events to essentially prevent, i.e., 'fixing' the pages from being turned 'back' to the front, or 'forward' to the back:

startedTurning: function(event,pageObject,corner){
    var thisPageNum = pageObject.page \* 1;
    var pageCnt = $(this).turn('pages') \* 1; 
    if ((thisPageNum < 3) || (thisPageNum >= pageCnt - 1)){
        event.preventDefault();
    }
},

inTurning: function(event,page,view){
    var pageCnt = $(this).turn('pages') \* 1;
    if ((page < 3) || (page >= pageCnt - 1))
        event.preventDefault();
},

Again, _my_ solution works because I _never_ want my users to go to the front or back covers.  Since your book starts out on the front cover, they obviously need to 'turn' the page to pages 2/3.  So, you'd have to modify my logic a bit to allow them to turn the page if they're already 'on' page 1.  Am I right to understand that you do NOT want users ever turning back to the front cover?  If not, what is the point of the 'fixed' class usage?

-David

**Comment by richardwestenra** [comment]
Sorry David, I'm not sure that I understand you correctly, but I suspect that that approach wouldn't work for me, because I need the book's front cover to be accessible, and the 'fixed' class flashes whether you're on the front cover or not. Anyway, after hours of trial and error I've found a fix. I applied an inner cover class to all the pages, and used the following code to remove the class from the pages that are being turned at the start of the turn, so that they don't have a piece of cover on turn. It's a bit hacky but it works:

$('.flipbook').turn({
    when: {
        start: function(e, page, view) {
            var book = $(this),
                currentPage = book.turn('page'),
                pages = book.turn('pages');
            for(var i=3; i<pages; i++){
                if(i==page.page || i==page.next) {
                    $('.p'+i).removeClass('innerCover');
                } else {
                    $('.p'+i).addClass('innerCover');
                }
            }
        }
    }
});
