### ISSUE TITLE
Button inside a page doesn't work with Rc3

### ISSUE THREAD

**Issue by yaffar666** [blasten/turn.js#46]
Greetings Blasten.

I already download the last Rc (3), i did replace it on my book but it raised an issue.
Inside a page I have a button which onload is attached to its click event through jquery just like this:

$('.imageViewerSwitch').click(function(e) {...});

The fact is that the button with the rc3 doesn't works, the click event is not fired anymore. When I reverse the version to Rc2 it works fine.

Thanks for your help.

**Comment by blasten** [comment]
You right!  The reason is the new way that turn.js uses to store pages.  It is fixable with just replacing your `click` with `live('click', function(e){})` What happens is that now, turn.js is removing some pages from the DOM and memory, and seems like jQuery is removing the list of listeners as well, which is smart, but doesn't work for turn.js. However `live` attach an event handler for all elements which match the current selector, now and in the future.
http://api.jquery.com/live/
