### ISSUE TITLE
Changing Pages from 112 to dynamic in steve-jobs error

### ISSUE THREAD

**Issue by umairlodhi** [blasten/turn.js#610]
Hi every one! i am new here, 
i am creating a dynamic bookview using steve-jobs but the issue is when i change 

> pages 112

 to any other number it stops working, and showing this error in console 
```
TurnJsError
message
:
"Page "111" cannot be inserted"
name
:
"TurnJsError"
```
i am working on this issue but unable to get the solutions, i really appreciate your help thanks

**Comment by linhaibo147** [comment]
hello,this problem is  
![qq 20171203222602](https://user-images.githubusercontent.com/20526897/33526230-fe7736d2-d878-11e7-9a90-5996e7b9d1c9.png)
![qq 20171203222610](https://user-images.githubusercontent.com/20526897/33526231-feb71338-d878-11e7-817b-09b3760af09f.png)

DIV P111   ,because js is select p111,but no p111 will damage book interface

**Comment by ashvechikov** [comment]
> hello,this problem is
> ![qq 20171203222602](https://user-images.githubusercontent.com/20526897/33526230-fe7736d2-d878-11e7-9a90-5996e7b9d1c9.png)
> ![qq 20171203222610](https://user-images.githubusercontent.com/20526897/33526231-feb71338-d878-11e7-817b-09b3760af09f.png)
> 
> DIV P111 ,because js is select p111,but no p111 will damage book interface

Thanks! It is great!

**Comment by ashvechikov** [comment]
Just change .p111 to .pN-1 , where N - max page count for you
And .p112 to .pN , where N - max page count for you

It works for me
