### ISSUE TITLE
Ability to add/remove pages dynamically

### ISSUE THREAD

**Issue by andyhass** [blasten/turn.js#7]
It would be great to add and remove pages dynamically after an instance is created.

**Comment by blasten** [comment]
Yes, it will be a feature of the next version of turn.js

**Comment by obsergiu** [comment]
Hi, you made a great plugin, first of all thank very much! 

I post here because i was wondering when do you think there will be the next version. I'm in a difficult position i really like you plugin and was very impressed and decided to use it on a website it works great but we need to add pages dynamically and because of lack of time we must change it to something else. Anyway i decided to ask you if in the very near future maybe you will add this ability.

Thx. a lot for your work.

**Comment by blasten** [comment]
Hello, Yes! the next version will include a new method to update the internal pages. You could use it right after change the composition of your magazine or book with jQuery. I hope to release the new version very soon.
