### ISSUE TITLE
C is undefined

### ISSUE THREAD

**Issue by mfrajesh** [blasten/turn.js#92]
Hi ,
       i am using this turn.js 3 in a modal window,
for the first time it is working fine when i close the modal window and open it again it is giving me this error,
can you help me on this issue.

i am getting the error in the following lines of the code

_eventMove: function (a) {
                var b = this.data(),
                c = b.pageFlip,
                    a = t ? a.originalEvent.touches : [a];
                c.disabled || (c.cornerActivated ? (b = c.parent.offset(), h._showThumbIndex.apply(this, [{
                    corner: c.cornerActivated.corner,
                    x: a[0].pageX - b.left,
                    y: a[0].pageY - b.top
                }])) : !b.effect && !t && ((corner = h._cornerActivated.apply(this, [a[0]])) ? (a = h._c.apply(this, [corner.corner, c.opt.cornerSize / 2]), h._showThumbIndex.apply(this, [{
                    corner: corner.corner,
                    x: a.x,
                    y: a.y
                }, !0])) : h.hideThumbIndex.apply(this, [!0])))
            },

to be precise i am getting the error in this line " c.disabled || (c.cornerActivated ? (b = c.parent.offset(), h._showThumbIndex.apply(this, [{"

**Comment by blasten** [comment]
Can you copy the error?  is it an undefined problem?

**Comment by mfrajesh** [comment]
Hi,
    I have attached the screenshot of the error.

_Thanks & Regards,_
Rajesh . M

On Fri, Jun 1, 2012 at 9:56 AM, Emmanuel Garcia <
reply@reply.github.com

**Comment by blasten** [comment]
Sorry, I didn't get the screenshot.

**Comment by puckettgw** [comment]
I am having the same issue (edit: mine says "b is undefined" rather than "c").. The following steps should help you reproduce the problem in firefox:

1) Create a div
2) Use jquery to load an html page with a few-page book into the div. The page should have $('element').turn() in a document ready function.
3) Use jquery to load a different html page into the same div
4) Notice that the javascript console in Firefox goes INSANE with errors (every single time the mouse moves, it generates an undefined error.) 
5) Attempt to reload the book HTML into the div. Also notice that attempting to grab the pages doesn't work at all, and using a keyboard event to flip them will flip all of them and cause some weird css effects.

I've also tried wrapping the book in a container div and using $('#container').ready() to initialize the book, but that still doesn't work.

I'm guessing however you find the 'hot corners' for the book pages can't handle the element disappearing and re-appearing later.

I'm not much of a JS programmer, but hopefully my input helps figure out this issue.

**Comment by blasten** [comment]
@puckettgw Is it turn.js 3? Please, could you please upload your sample to http://jsfiddle.net/?

**Comment by puckettgw** [comment]
@blasten Yes, it's turn.js 3. I'll work on making a sample to reproduce the bug.. I can't share the page I originally discovered it on. I'll let you know when I've posted it.

**Comment by puckettgw** [comment]
@blasten 
http://jsfiddle.net/phQDE/ 
^ Please read the comments in it, you'll have to adjust it to work on jsfiddle (I'm new to jsfiddle and can't get it to work right.) It's a very simple example.

**Comment by blasten** [comment]
Is `#container`  wrapping `.book`? In your sample it doesn't, it's actually one more element in body, and I don't see any problem with that.  If `#container` is wrapping `.book` and you are intending to remove the flipbook by just replacing the HTML for something else, it would reproduce the problem you mentioned. Turn.js 4th release includes a destroy method, which allows you to do what you are basically doing.

So, assuming that `.book` is in `#container`, with turn.js 4 you can do this:

``` javascript
$('#container .book').turn('destroy').remove();
$('#container').html(SomethingElse);
```

**Comment by puckettgw** [comment]
@blasten #container is supposed to be empty at page load and then have #book loaded into it from another file via AJAX (as per the comments in the source).. So container _would_ be wrapping it if i knew how to work jsfiddle. :]

However, the destroy method is pretty much exactly what I've been looking for, I think. I'll have to see if turn.js 4 fixes the problem (when I have the money for a commercial license.) Thanks for the quick response!
